<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Hero', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":1145,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/floor-interior-home-ceiling-loft-office-1390062-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":3,"g":3,"b":3,"a":0.8},"image":{"Desktop":{"id":1119,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/line.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"260","bottom":"180","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"220","bottom":"120","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"200","bottom":"100","right":"10","left":"10"}}}} -->
			<div class="section-wrapper" data-id="9rsSZi"><script>var top9rsSZi = {"Desktop":{"point":"0","unit":"px"}};var bottom9rsSZi = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-9rsSZi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-vhOgUa","horizontalAlign":{"Desktop":"center","Mobile":"center","Tablet":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vhOgUa"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vhOgUa"><script>var topvhOgUa = {"Desktop":{"point":"0","unit":"px"}};var bottomvhOgUa = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:post-title {"textAlign":"center","style":{"typography":{"fontSize":"48px","fontStyle":"normal","fontWeight":"600"}},"textColor":"intrace-accent","fontFamily":"primary"} /--></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
